/*
 * Copyright (C) 2015 Jolla Ltd.
 * Contact: Slava Monich <slava.monich@jolla.com>
 *
 * You may use this file under the terms of the BSD license as follows:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *   * Neither the name of Nemo Mobile nor the names of its contributors
 *     may be used to endorse or promote products derived from this
 *     software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <libudev.h>
#include <stdlib.h>
#include <dlfcn.h>

#define LIBUDEV_FUNCTIONS(f) \
    f(struct udev*, udev_unref,\
     (struct udev* udev), \
     (udev)) \
    f(struct udev_monitor*, udev_monitor_new_from_netlink, \
     (struct udev* udev, const char* name), \
     (udev, name)) \
    f(struct udev_device*, udev_monitor_receive_device, \
     (struct udev_monitor* mon), \
     (mon)) \
    f(int, udev_monitor_filter_add_match_subsystem_devtype, \
     (struct udev_monitor* mon, const char* sub, const char* dev), \
     (mon, sub, dev)) \
    f(int, udev_monitor_enable_receiving, \
     (struct udev_monitor* mon), \
     (mon)) \
    f(int, udev_monitor_get_fd, \
     (struct udev_monitor* mon), \
     (mon)) \
    f(struct udev_monitor*, udev_monitor_unref, \
     (struct udev_monitor* mon), \
     (mon)) \
    f(const char*, udev_device_get_devnode, \
     (struct udev_device* dev), \
     (dev)) \
    f(const char*, udev_device_get_devpath, \
     (struct udev_device* dev), \
     (dev)) \
    f(const char*, udev_device_get_subsystem, \
     (struct udev_device* dev), \
     (dev)) \
    f(const char*, udev_device_get_devtype, \
     (struct udev_device* dev), \
     (dev)) \
    f(const char*, udev_device_get_action, \
     (struct udev_device* dev), \
     (dev)) \
    f(struct udev_device*, udev_device_unref, \
     (struct udev_device* dev), \
     (dev))

#define LIBUDEV_NUM_FUNCTIONS (sizeof(libudev_names)/sizeof(libudev_names[0]))
#define LIBUDEV_NO_HANDLE     ((void*)-1)
#define LIBUDEV_SO            "/usr/lib/libudev.so.1"

static const char* libudev_names[] = {
    "udev_new",
    #define FN_NAME(ret,name,params,args) #name,
    LIBUDEV_FUNCTIONS(FN_NAME)
};

static struct {
    void* handle;
    union {
        struct libudev_proc {
            struct udev* (*udev_new)(void);
            #define FN_POINTER(ret,name,params,args) ret (* name) params;
            LIBUDEV_FUNCTIONS(FN_POINTER)
        } udev;
        void* entry[LIBUDEV_NUM_FUNCTIONS];
    } fn;
} libudev;

/* udev_new() is the special function where we load the library */
struct udev*
udev_new()
{
    if (!libudev.handle) {
        libudev.handle = dlopen(LIBUDEV_SO, RTLD_LAZY);
        if (libudev.handle) {
            unsigned int i;
            for (i=0; i<LIBUDEV_NUM_FUNCTIONS; i++) {
                libudev.fn.entry[i] = dlsym(libudev.handle, libudev_names[i]);
            }
        } else {
            libudev.handle = LIBUDEV_NO_HANDLE;
        }
    }
    return libudev.fn.udev.udev_new ? libudev.fn.udev.udev_new() : NULL;
}

/* All other wrappers are generated by the preprocessor */
#define FN_IMPL(ret,name,params,args) ret name params \
  { return libudev.fn.udev.name ? libudev.fn.udev.name args : 0; }
LIBUDEV_FUNCTIONS(FN_IMPL)
